version: '3.8'
services:
  mcp:
    build: ./mcp
    env_file: .env
    ports:
      - "5000:5000"
  bot:
    build: ./bot
    env_file: .env
    ports:
     - "50934:3978"
    depends_on:
      - mcp
